### ISSUE TITLE
[InvalidArgumentException]

### ISSUE THREAD

**Issue by HamidVetr** [Nks/laravel-instagram-api#1]
when I try to install the package it gives me this error
```

[InvalidArgumentException]
  Could not find package nakukryskin/laravel-instagram-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by Nks** [comment]
@HamidVetr try add `"minimum-stability": "dev",` to your composer.json.
Regarding this package - it can't be stable right now because it using an unstable code from InstagramAPI.
